### ISSUE TITLE
Parameters not working in @aws-sdk/client-redshift-data

### ISSUE THREAD

**Issue by henrybzhang** [aws-samples/getting-started-with-amazon-redshift-data-api#3]
The following command in a lambda function throws a ValidationError when sent to the client.
```js
var _clientRedshiftData = require("@aws-sdk/client-redshift-data");

const client = new _clientRedshiftData.RedshiftDataClient({
  region: 'us-east-1'
});

const UPDATE_QUERY = "\
  UPDATE schema.user \
  SET \
    email = @email \
  WHERE id = @id;";

exports.handler = async (event, context) => {
  const results = await Promise.all(events.Records.map(async (record) => {
    const command = new _clientRedshiftData.ExecuteStatementCommand({
      ClusterIdentifier: 'cluster-test',
      Database: 'database',
      DbUser: 'user',
      Sql: UPDATE_QUERY,
      Parameters: [
        { name: "@id", value: 'sampleId' },
        { name: "@email", value: 'sample@gmail.com' },
      ]
    });
    return (await client.send(command));
  }
}
```
```
{
    "errorType": "ValidationException",
    "errorMessage": "ValidationException",
    "name": "ValidationException",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 400,
        "requestId": "d866b77e-184c-4da9-b4cf-45bc7fd3d556",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "ValidationException: ValidationException",
        "    at deserializeAws_json1_1ExecuteStatementCommandError (/opt/nodejs/node_modules/@aws-sdk/client-redshift-data/dist-cjs/protocols/Aws_json1_1.js:411:41)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
        "    at async /opt/nodejs/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20",
        "    at async /opt/nodejs/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20",
        "    at async StandardRetryStrategy.retry (/opt/nodejs/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)",
        "    at async /opt/nodejs/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22",
        "    at async /var/task/index.js:156:13",
        "    at async Promise.all (index 0)",
        "    at async Runtime.exports.handler (/var/task/index.js:66:19)"
    ]
}
```
However, when I take out `Parameters`, the query works fine.

**Comment by itsDZhang** [comment]
Hi @henrybzhang 

Does this work?
```js
Parameters: [
  { '@id': 'sampleId' },
  { '@email': 'sample@gmail.com' },
]
```

OR

```js
  Parameters: [
    { 'name': '@id', 'value': 'sampleId' },
    { 'name': '@email', 'value' : 'sample@gmail.com' },
  ]
```

**Comment by itsDZhang** [comment]
@henrybzhang 

Single quotes are not supported in parameterization. Please reopen this ticket if the issue is not resolved.
